// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sitram.Infrastructure.Persistence;

#nullable disable

namespace Sitram.Infrastructure.Migrations
{
    [DbContext(typeof(SitramDbContext))]
    partial class SitramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Ciudadanos.Ciudadano", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Correo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Dni")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("EstaAnonimizado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Telefono")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Ciudadanos", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Ciudadanos.Consentimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CiudadanoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Finalidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Otorgado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevocadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.ToTable("Consentimientos", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Pagos.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReferenciaPasarela")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TramiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TramiteId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Seguridad.IncidenteSeguridad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaDeteccionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNotificacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OficialNotificadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolucion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("IncidentesSeguridad", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.PasoFlujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RolResponsableId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoTramiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoTramiteId");

                    b.ToTable("PasosFlujo", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.RequisitoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("boolean");

                    b.Property<int?>("TipoTramiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoTramiteId");

                    b.ToTable("RequisitosDocumento", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.TipoTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaResponsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("TiposTramite", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Actuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TramiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TramiteId");

                    b.ToTable("Actuaciones", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("SubidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TramiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TramiteId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Tramite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertaVencimientoEnviada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CiudadanoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaLimiteSubsanacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoTramiteId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("TipoTramiteId");

                    b.ToTable("Tramites", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PermisoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevocadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Identity.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "RolId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Sitram.Infrastructure.Persistence.EventoAuditoria", b =>
                {
                    b.Property<long>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventoId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("text");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("text");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TramiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("EventoId");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("TramiteId");

                    b.ToTable("EventosAuditoria", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sitram.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sitram.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sitram.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sitram.Domain.Ciudadanos.Consentimiento", b =>
                {
                    b.HasOne("Sitram.Domain.Ciudadanos.Ciudadano", null)
                        .WithMany("Consentimientos")
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sitram.Domain.Pagos.Pago", b =>
                {
                    b.HasOne("Sitram.Domain.Tramites.Tramite", null)
                        .WithMany()
                        .HasForeignKey("TramiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.PasoFlujo", b =>
                {
                    b.HasOne("Sitram.Domain.TiposTramite.TipoTramite", null)
                        .WithMany("PasosFlujo")
                        .HasForeignKey("TipoTramiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.RequisitoDocumento", b =>
                {
                    b.HasOne("Sitram.Domain.TiposTramite.TipoTramite", null)
                        .WithMany("Requisitos")
                        .HasForeignKey("TipoTramiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Actuacion", b =>
                {
                    b.HasOne("Sitram.Domain.Tramites.Tramite", null)
                        .WithMany("Historial")
                        .HasForeignKey("TramiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Documento", b =>
                {
                    b.HasOne("Sitram.Domain.Tramites.Tramite", null)
                        .WithMany("Documentos")
                        .HasForeignKey("TramiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Tramite", b =>
                {
                    b.HasOne("Sitram.Domain.TiposTramite.TipoTramite", null)
                        .WithMany()
                        .HasForeignKey("TipoTramiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sitram.Domain.Ciudadanos.Ciudadano", b =>
                {
                    b.Navigation("Consentimientos");
                });

            modelBuilder.Entity("Sitram.Domain.TiposTramite.TipoTramite", b =>
                {
                    b.Navigation("PasosFlujo");

                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("Sitram.Domain.Tramites.Tramite", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
